[[redirects]]
from = "https://maxthecreative-prod.netlify.com/*"
to = "https://maxthecreative.co/:splat"
status = 301
force = true

[[redirects]]
from = "http://maxthecreative-prod.netlify.com/*"
to = "http://maxthecreative.co/:splat"
status = 301
force = true

[[redirects]]
from = "http://maxthecreative.co/*"
to = "https://maxthecreative.co/:splat"
status = 301
force = true